### ISSUE TITLE
I keep getting this error on my server.

### ISSUE THREAD

**Issue by KofiFS** [decodinatorX/Liroth-Revamped-Fabric#14]
[06.10 22:07:22] [Multicraft] Starting server!
[06.10 22:07:22] [Multicraft] Loaded config for "Default"
[06.10 22:07:22] [Multicraft] JAR file not found, copying from global JAR directory
[06.10 22:07:22] [Multicraft] Failed to copy jarfile from global JAR directory
[06.10 22:07:22] [Multicraft] JAR file not found. Go to "Settings"-"Update Minecraft" to download the JAR file.
[06.10 22:07:22] [Multicraft] Updating eula.txt file
[06.10 22:07:23] [Server] ErrorUnable to access jarfile /forge-1.19.2-43.1.33.jar
[06.10 22:07:23] [Multicraft] Server shut down (starting)
[06.10 22:07:23] [Multicraft] Restarting crashed server in 2.0 seconds
[06.10 22:07:23] [Multicraft] Looks like a crash, check the server console. Return value: 1
[06.10 22:07:23] [Multicraft] Server stopped
[06.10 22:07:25] [Multicraft] Loading server properties
[06.10 22:07:25] [Multicraft] Starting server!
[06.10 22:07:25] [Multicraft] Loaded config for "Default"
[06.10 22:07:26] [Multicraft] Received start command
[06.10 22:07:26] [Multicraft] Server currently starting but process has gone away, restarting
[06.10 22:07:26] [Multicraft] Server stopped
[06.10 22:07:36] [Multicraft] Loading server properties
[06.10 22:07:36] [Multicraft] Starting server!
[06.10 22:07:37] [Multicraft] Loaded config for "Default"
[06.10 22:07:38] [Multicraft] Updating eula.txt file
[06.10 22:07:40] [Server] [Log4jPatch] [INFO] Patching org/apache/logging/log4j/core/pattern/MessagePatternConverter
[06.10 22:07:40] [Server] [Log4jPatch] [WARN] Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
[06.10 22:07:40] [Server] [Log4jPatch] [INFO] Patching org/apache/logging/log4j/core/lookup/JndiLookup
[06.10 22:07:40] [Server] 2022-10-22:07:40,770 main WARN Advanced terminal features are not available in this environment
[06.10 22:07:40] [Server] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 43.1.33, --fml.mcVersion, 1.19.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220805.130853, nogui]
[06.10 22:07:40] [Server] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.1 by Oracle Corporation; OS Linux arch amd64 version 4.15.0-189-generic
[06.10 22:07:41] [Server] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2363!/ Service=ModLauncher Env=SERVER
[06.10 22:07:42] [Server] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /libraries/net/minecraftforge/fmlcore/1.19.2-43.1.33/fmlcore-1.19.2-43.1.33.jar is missing mods.toml file
[06.10 22:07:42] [Server] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /libraries/net/minecraftforge/javafmllanguage/1.19.2-43.1.33/javafmllanguage-1.19.2-43.1.33.jar is missing mods.toml file
[06.10 22:07:42] [Server] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /libraries/net/minecraftforge/lowcodelanguage/1.19.2-43.1.33/lowcodelanguage-1.19.2-43.1.33.jar is missing mods.toml file
[06.10 22:07:42] [Server] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /libraries/net/minecraftforge/mclanguage/1.19.2-43.1.33/mclanguage-1.19.2-43.1.33.jar is missing mods.toml file
[06.10 22:07:42] [Server] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 7 dependencies adding them to mods collection
[06.10 22:07:45] [Server] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[06.10 22:07:45] [Server] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [tictim.paraglider.MixinConnector]
[06.10 22:07:45] [Server] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[06.10 22:07:45] [Server] [main/WARN] [mixin/]: Reference map 'morevillagers-forge-forge-refmap.json' for morevillagers.mixins.json could not be read. If this is a development environment you can ignore this message
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: Error loading class: shadows/apotheosis/ench/table/ApothEnchantContainer (java.lang.ClassNotFoundException: shadows.apotheosis.ench.table.ApothEnchantContainer)
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: @Mixin target shadows.apotheosis.ench.table.ApothEnchantContainer was not found origins_classes.mixins.json:common.apotheosis.ApotheosisEnchantmentMenuMixin
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: Error loading class: se/mickelus/tetra/blocks/workbench/WorkbenchTile (java.lang.ClassNotFoundException: se.mickelus.tetra.blocks.workbench.WorkbenchTile)
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: @Mixin target se.mickelus.tetra.blocks.workbench.WorkbenchTile was not found origins_classes.mixins.json:common.tetra.WorkbenchTileMixin
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/entity/PhantomRenderer (java.lang.ClassNotFoundException: net.minecraft.client.renderer.entity.PhantomRenderer)
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.entity.PhantomRenderer was not found deeperdarker.mixins.json:PhantomRendererMixin
[06.10 22:07:47] [Server] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/Minecraft (java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER)
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.Minecraft was not found playerrevive.mixins.json:MinecraftAccessor
[06.10 22:07:47] [Server] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/player/LocalPlayer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER)
[06.10 22:07:47] [Server] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.player.LocalPlayer was not found playerrevive.mixins.json:LocalPlayerAccessor
[06.10 22:07:53] [Server] [main/INFO] [minecraft/DataFixers]: Building unoptimized datafixer
[06.10 22:07:56] [Server] [modloading-worker-0/INFO] [io.gi.ap.or.Origins/]: Origins 1.19.2-1.5.0.6 is initializing. Have fun!
[06.10 22:07:56] [Server] [Modding Legacy/blue_skies/Supporters thread/INFO] [ModdingLegacy/blue_skies/Supporter/]: Attempting to load the Modding Legacy supporters list from https://moddinglegacy.com/supporters-changelogs/supporters.txt
[06.10 22:07:56] [Server] [modloading-worker-0/INFO] [de.li.or.OriginsClasses/]: Origins:Classes 1.2.0 has initialized. Time for work!
[06.10 22:07:57] [Server] [modloading-worker-0/INFO] [Puzzles Lib/]: Constructing common components for mod easymagic
[06.10 22:07:57] [Server] [modloading-worker-0/INFO] [de.ar.ne.fo.NetworkManagerImpl/]: Registering C2S receiver with id architectury:sync_ids
[06.10 22:07:57] [Server] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 43.1.33, for MC 1.19.2 with MCP 20220805.130853
[06.10 22:07:57] [Server] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v43.1.33 Initialized
[06.10 22:07:57] [Server] [modloading-worker-0/INFO] [xy.ap.fo.co.Mo.CommonalityMod/]: Running Minecraft '1.19.2', & Forge '43.1.33' on Java '17.0.1, Oracle Corporation'
[06.10 22:07:57] [Server] [modloading-worker-0/INFO] [TrustedSourceList/]: Loading BlackListed sources from remote... (https://api.stopmodreposts.org/minecraft/sites.txt)
[06.10 22:07:57] [Server] [modloading-worker-0/INFO] [Calio/]: Calio 1.19.2-1.6.0.3 initializing...
[06.10 22:07:57] [Server] [modloading-worker-0/OFF] [co.gi.dr.dr.Dreamland/]: Registering Dreamland Sound Types...
[06.10 22:07:58] [Server] [modloading-worker-0/INFO] [TrustManager/]: Loading mod 'fantasyfurniture' TrustWorthiness...
[06.10 22:07:58] [Server] [modloading-worker-0/INFO] [thedragonlib/]: Welcoming Minecraft
[06.10 22:07:58] [Server] [modloading-worker-0/FATAL] [TrustManager/]: Could not determine mod trust worthiness, Assuming Jar was downloaded from trusted source!
[06.10 22:07:58] [Server] [modloading-worker-0/INFO] [TrustManager/]: Loaded mod 'fantasyfurniture' TrustWorthiness: UNKNOWN
[06.10 22:07:58] [Server] [modloading-worker-0/INFO] [Puzzles Lib/]: Constructing common components for mod puzzleslib
[06.10 22:07:58] [Server] [modloading-worker-0/INFO] [TrustManager/]: Loading mod 'apexcore' TrustWorthiness...
[06.10 22:07:58] [Server] [modloading-worker-0/FATAL] [TrustManager/]: Could not determine mod trust worthiness, Assuming Jar was downloaded from trusted source!
[06.10 22:07:58] [Server] [modloading-worker-0/INFO] [TrustManager/]: Loaded mod 'apexcore' TrustWorthiness: UNKNOWN
[06.10 22:07:58] [Server] [Modding Legacy/blue_skies/Supporters thread/INFO] [ModdingLegacy/blue_skies/Supporter/]: Successfully loaded the Modding Legacy supporters list.
[06.10 22:07:58] [Server] [modloading-worker-0/INFO] [TrustedSourceList/]: Loaded 553 BlackListed sources from remote
[06.10 22:07:58] [Server] [modloading-worker-0/INFO] [TrustManager/]: Loading mod 'commonality' TrustWorthiness...
[06.10 22:07:58] [Server] [modloading-worker-0/FATAL] [TrustManager/]: Could not determine mod trust worthiness, Assuming Jar was downloaded from trusted source!
[06.10 22:07:58] [Server] [modloading-worker-0/INFO] [TrustManager/]: Loaded mod 'commonality' TrustWorthiness: UNKNOWN
[06.10 22:07:58] [Server] [modloading-worker-0/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: liroth, class com.decodinator.liroth.Liroth
[06.10 22:07:58] [Server] java.lang.reflect.InvocationTargetExceptionnull
[06.10 22:07:58] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[06.10 22:07:58] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[06.10 22:07:58] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[06.10 22:07:58] [Server] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[06.10 22:07:58] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[06.10 22:07:58] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.33.jar%23204!/:?] {}
[06.10 22:07:58] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.33.jar%23203!/:?] {}
[06.10 22:07:58] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
[06.10 22:07:58] [Server] 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
[06.10 22:07:58] [Server] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
[06.10 22:07:58] [Server] 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
[06.10 22:07:58] [Server] 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
[06.10 22:07:58] [Server] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
[06.10 22:07:58] [Server] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
[06.10 22:07:58] [Server] Caused byjava.lang.NoClassDefFoundError: net/minecraft/client/model/geom/ModelLayerLocation
[06.10 22:07:58] [Server] 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
[06.10 22:07:58] [Server] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
[06.10 22:07:58] [Server] 	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
[06.10 22:07:58] [Server] 	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
[06.10 22:07:58] [Server] 	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:100) ~[eventbus-6.0.3.jar%2351!/:?] {}
[06.10 22:07:58] [Server] 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.3.jar%2351!/:?] {}
[06.10 22:07:58] [Server] 	at com.decodinator.liroth.Liroth.<init>(Liroth.java:140) ~[Liroth-R_1.0.3-1.19.2.jar%23154!/:1.{re:classloading}
[06.10 22:07:58] [Server] 	... more
[06.10 22:07:58] [Server] Caused byjava.lang.ClassNotFoundException: net.minecraft.client.model.geom.ModelLayerLocation
[06.10 22:07:58] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
[06.10 22:07:58] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[06.10 22:07:58] [Server] 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
[06.10 22:07:58] [Server] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
[06.10 22:07:58] [Server] 	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
[06.10 22:07:58] [Server] 	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
[06.10 22:07:58] [Server] 	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:100) ~[eventbus-6.0.3.jar%2351!/:?] {}
[06.10 22:07:58] [Server] 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.3.jar%2351!/:?] {}
[06.10 22:07:58] [Server] 	at com.decodinator.liroth.Liroth.<init>(Liroth.java:140) ~[Liroth-R_1.0.3-1.19.2.jar%23154!/:1.{re:classloading}
[06.10 22:07:58] [Server] 	... more
[06.10 22:07:58] [Server] [modloading-worker-0/OFF] [co.gi.dr.dr.Dreamland/]: Registering Dreamland Wood Sets...
[06.10 22:07:59] [Server] [modloading-worker-0/INFO] [io.gi.ap.ap.Apoli/]: Apoli 1.19.2-2.3.4.4 has initialized. Ready to power up your game!
[06.10 22:07:59] [Server] [main/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[06.10 22:07:59] [Server] Negative index in crash report handler (16/18)
[06.10 22:07:59] [Server] [main/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 9e1866e2-f46e-41ef-a8ce-1d55a58374b2
[06.10 22:07:59] [Server] [main/FATAL] [ne.mi.se.lo.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2022-10-06_22.07.59-fml.txt
[06.10 22:07:59] [Server] [main/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 8cdd5c19-d227-4d48-923f-b8788586c5fe
[06.10 22:07:59] [Server] ---- Minecraft Crash Report ----
[06.10 22:07:59] [Server] // Don't be sad. I'll do better next time, I promise!
[06.10 22:07:59] [Server] Time2022-10-06 22:07:59
[06.10 22:07:59] [Server] DescriptionMod loading error has occurred
[06.10 22:07:59] [Server] java.lang.ExceptionMod Loading has failed
[06.10 22:07:59] [Server] 	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.1.33-universal.jar%23207!/:?] {re:classloading}
[06.10 22:07:59] [Server] 	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.19.2-43.1.33-universal.jar%23207!/:?] {re:classloading}
[06.10 22:07:59] [Server] 	at net.minecraft.server.Main.main(Main.java:113) ~[server-1.19.2-20220805.130853-srg.jar%23202!/:?] {re:classloading,re:mixin,pl:mixin:A}
[06.10 22:07:59] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
[06.10 22:07:59] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
[06.10 22:07:59] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
[06.10 22:07:59] [Server] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
[06.10 22:07:59] [Server] 	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.1.33.jar%2367!/:?] {}
[06.10 22:07:59] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
[06.10 22:07:59] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
[06.10 22:07:59] [Server] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
[06.10 22:07:59] [Server] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2354!/:?] {}
[06.10 22:07:59] [Server] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2354!/:?] {}
[06.10 22:07:59] [Server] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
[06.10 22:07:59] [Server] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
[06.10 22:07:59] [Server] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
[06.10 22:07:59] [Server] A detailed walkthrough of the error, its code path and all known details is as follows:
[06.10 22:07:59] [Server] ---------------------------------------------------------------------------------------
[06.10 22:07:59] [Server] -- Head --
[06.10 22:07:59] [Server] Threadmain
[06.10 22:07:59] [Server] Stacktrace:
[06.10 22:07:59] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
[06.10 22:07:59] [Server] -- MOD liroth --
[06.10 22:07:59] [Server] Details:
[06.10 22:07:59] [Server] 	Caused by java.lang.reflect.InvocationTargetException
[06.10 22:07:59] [Server] 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[06.10 22:07:59] [Server] 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[06.10 22:07:59] [Server] 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[06.10 22:07:59] [Server] 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.33.jar%23204!/:?] {}
[06.10 22:07:59] [Server] 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.33.jar%23203!/:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
[06.10 22:07:59] [Server] 	Caused by java.lang.NoClassDefFoundError: net/minecraft/client/model/geom/ModelLayerLocation
[06.10 22:07:59] [Server] 		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
[06.10 22:07:59] [Server] 		at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
[06.10 22:07:59] [Server] 		at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
[06.10 22:07:59] [Server] 		at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
[06.10 22:07:59] [Server] 		at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:100) ~[eventbus-6.0.3.jar%2351!/:?] {}
[06.10 22:07:59] [Server] 		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.3.jar%2351!/:?] {}
[06.10 22:07:59] [Server] 		at com.decodinator.liroth.Liroth.<init>(Liroth.java:140) ~[Liroth-R_1.0.3-1.19.2.jar%23154!/:1.{re:classloading}
[06.10 22:07:59] [Server] 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[06.10 22:07:59] [Server] 		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[06.10 22:07:59] [Server] 		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[06.10 22:07:59] [Server] 		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.33.jar%23204!/:?] {}
[06.10 22:07:59] [Server] 		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.33.jar%23203!/:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
[06.10 22:07:59] [Server] 		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
[06.10 22:07:59] [Server] 	Mod File/mods/Liroth-R_1.0.3-1.19.2.jar
[06.10 22:07:59] [Server] 	Failure messageLiroth Revamped (liroth) has failed to load correctly
[06.10 22:07:59] [Server] 		java.lang.reflect.InvocationTargetExceptionnull
[06.10 22:07:59] [Server] 	Mod Version1.0
[06.10 22:07:59] [Server] 	Mod Issue URLNOT PROVIDED
[06.10 22:07:59] [Server] 	Exception messagejava.lang.ClassNotFoundException: net.minecraft.client.model.geom.ModelLayerLocation
[06.10 22:07:59] [Server] Stacktrace:
[06.10 22:07:59] [Server] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
[06.10 22:07:59] [Server] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
[06.10 22:07:59] [Server] 	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
[06.10 22:07:59] [Server] 	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
[06.10 22:07:59] [Server] 	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
[06.10 22:07:59] [Server] 	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
[06.10 22:07:59] [Server] 	at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:100) ~[eventbus-6.0.3.jar%2351!/:?] {}
[06.10 22:07:59] [Server] 	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.3.jar%2351!/:?] {}
[06.10 22:07:59] [Server] 	at com.decodinator.liroth.Liroth.<init>(Liroth.java:140) ~[Liroth-R_1.0.3-1.19.2.jar%23154!/:1.{re:classloading}
[06.10 22:07:59] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
[06.10 22:07:59] [Server] 	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
[06.10 22:07:59] [Server] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
[06.10 22:07:59] [Server] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
[06.10 22:07:59] [Server] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
[06.10 22:07:59] [Server] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.1.33.jar%23204!/:?] {}
[06.10 22:07:59] [Server] 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.33.jar%23203!/:?] {}
[06.10 22:17:42] [Multicraft] Auto-saving world...

**Comment by decodinatorX** [comment]
Hi, I am going to close this issue because this is the FABRIC version of Liroth Revamped, not the FORGE version.

https://github.com/decodinatorX/Liroth-Revamped-Forge
