### ISSUE TITLE
Doesnt work in a server

### ISSUE THREAD

**Issue by itsdinkd** [decodinatorX/Liroth-Revamped-Fabric#4]
Not working for dedicated server instances.

```java
[23:19:26] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'liroth'!
        at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52) ~[?:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.2.jar:?]
        at net.minecraft.server.Main.main(Main:101) [server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.2.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.14.2.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_897
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.2.jar:?]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: can't find class net.minecraft.class_897
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.2.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.2.jar:?]
        ... 15 more

**Comment by itsdinkd** [comment]
You let me know when you're ready to update and I'll throw it in my modpack that will get you the downloads you deserve. Though, if twilight forest drops before this is updated I'll be sticking with that.

**Comment by decodinatorX** [comment]
Can you list your modpack?

**Comment by itsdinkd** [comment]
> Can you list your modpack?

https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2

**Comment by Tishbyte** [comment]
Adding to this, had the same issue. Not sure what the conflict is yet because I have to restart the server every time to test.

**Comment by Tishbyte** [comment]
I've gone through and removed all non-required mods and it still doesn't work on a server. Here is the latest log:
```
[22:40:39] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.3
[22:40:39] [main/INFO]: Loading 50 mods:
	- bclib 1.3.5
	- cloth-api 3.1.61
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-client-events-v0 3.1.61 via cloth-api
	- cloth-common-events-v1 3.1.61 via cloth-api
	- cloth-config 6.2.62
	- cloth-datagen-api-v1 3.1.61 via cloth-api
	- cloth-utils-v1 3.1.61 via cloth-api
	- customportalapi 0.0.1-beta49-1.18 via liroth
	- fabric 0.46.6+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.9+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.7+3ac43d9565 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.7+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.12+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.5+737332ce65 via fabric
	- fabric-object-builders-v0 0.7.13+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.15+8906aafd65 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.9+d7c144a865 via fabric
	- fabric-tool-attribute-api-v1 1.3.9+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.10+c329913d65 via fabric
	- fabricloader 0.13.3
	- feature_nbt_deadlock_be_gone 1.0.1+1.18.1
	- java 17
	- liroth 1.0.0
	- minecraft 1.18.1
	- no_null_processors 2.0.1+1.18.1
[22:40:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Storage-PC/Desktop/Minecraft%20Server/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[22:40:39] [main/INFO]: Compatibility level set to JAVA_17
[22:40:40] [main/WARN]: Error loading class: net/minecraft/class_638 (java.lang.ClassNotFoundException: net/minecraft/class_638)
[22:40:40] [main/WARN]: @Mixin target net.minecraft.class_638 was not found liroth.mixins.json:access.ClientLevelAccess
[22:40:40] [main/WARN]: Error loading class: net/minecraft/class_4696 (java.lang.ClassNotFoundException: net/minecraft/class_4696)
[22:40:40] [main/WARN]: @Mixin target net.minecraft.class_4696 was not found liroth.mixins.json:access.ItemBlockRenderTypeAccess
[22:40:40] [main/WARN]: Error loading class: net/minecraft/class_746 (java.lang.ClassNotFoundException: net/minecraft/class_746)
[22:40:40] [main/WARN]: @Mixin target net.minecraft.class_746 was not found liroth.mixins.json:bruh.ClientPlayerEntityMixin
[22:40:46] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zeh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[22:40:49] [main/INFO]: [bclib] Added Config bclib.main to auto sync (content diff)
[22:40:49] [main/INFO]: [bclib] Added Config bclib.recipes to auto sync (file hash)
[22:40:49] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'liroth'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.13.3.jar:?]
	at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_897
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_897
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.13.3.jar:?]
	... 15 more
```

**Comment by itsdinkd** [comment]
> Can you list your modpack?

Are you going to fix this? It seems like its been an issue since April 7th #2

**Comment by itsdinkd** [comment]
> Adding to this, had the same issue. Not sure what the conflict is yet because I have to restart the server every time to test.

Their mod is trying to run a client class in a server environment. its not a mod conflict. Easy fix.

**Comment by decodinatorX** [comment]
> > Adding to this, had the same issue. Not sure what the conflict is yet because I have to restart the server every time to test.
> 
> Their mod is trying to run a client class in a server environment. its not a mod conflict. Easy fix.

I had dropped the mod for a moment due to extreme burnout, I can faithfully say that I will be pushing two updates to Curseforge for 1.18.2 and the new updated 1.19.2 later today. Thank you for assisting me with the client/server-side conflict, helped me get a good direction on what was going wrong.

**Comment by Tishbyte** [comment]
> > > Adding to this, had the same issue. Not sure what the conflict is yet because I have to restart the server every time to test.
> > 
> > 
> > Their mod is trying to run a client class in a server environment. its not a mod conflict. Easy fix.
> 
> I had dropped the mod for a moment due to extreme burnout, I can faithfully say that I will be pushing two updates to Curseforge for 1.18.2 and the new updated 1.19.2 later today. Thank you for assisting me with the client/server-side conflict, helped me get a good direction on what was going wrong.

Thank you and I hope you are feeling better. Burnout is no fun.
Take it easy!
